language: objective-c
osx_image: xcode8.2

script:
  - xcodebuild test -workspace SwiftySignals.xcworkspace -scheme SwiftySignals-macOS
  - xcodebuild test -workspace SwiftySignals.xcworkspace -scheme SwiftySignals-iOS -destination "platform=iOS Simulator,OS=10.0,name=iPhone 6" -sdk iphonesimulator
  - xcodebuild test -workspace SwiftySignals.xcworkspace -scheme SwiftySignals-tvOS -destination "platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p" -sdk appletvsimulator
  - xcodebuild build -workspace SwiftySignals.xcworkspace -scheme SwiftySignals-watchOS -sdk watchsimulator

notifications:
email: true
